### ISSUE TITLE
swagger.json wrong?

### ISSUE THREAD

**Issue by senften** [rh072005/SwashbuckleAspNetVersioningShim#10]
I've been working with the following example code, https://github.com/PaddoSwam/AspNetCoreVersionedWebApi, using it and the basic setup from the README for SwashbuckleAspNetVersioningShim, to get ASP .Net Core versioning and swagger documentation generation working together.

The json file, http://localhost:5000/swagger/v2.0/swagger.json, generated by the example doesn't look right to me.

```
{
  "swagger": "2.0",
  "info": {
    "version": "2.0",
    "title": "API Version 2.0"
  },
  "basePath": "/",
  "paths": {
    "/api/v2.0/Hello": {
      "get": {
        "tags": [
          "Hello"
        ],
        "operationId": "ApiV{versionHelloGet",
        "consumes": [],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/HelloWorldModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "HelloWorldModel": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {}
}
```

I think the operationId is wrong and when used when swagger codegen to generated client side libraries creates odd name conventions. It appears that the operation wants to incorporate the version id into the function name, but json should be generated for a specific version so it's not clear to me what value there is in encoding that version id in the function names.

I am seeing similar behavior in my project where I have updated my dependencies to

```
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="1.1.0-rc1"/>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0"/>
    <PackageReference Include="SwashbuckleAspNetVersioningShim" Version="1.0.0-beta2"/>
```

Is this output expected?

**Comment by rh072005** [comment]
Cheers for raising this. The operation ids were wrong in previous versions but in one of the more recent versions of  ```Microsoft.AspNetCore.Mvc.Versioning``` they had started working again without me needing to make any changes. It looks like that may have changed again though and started producing weird operation ids.
I'll take a look at getting this resolved

**Comment by rh072005** [comment]
I've added a new operation filter that corrects the operation ids. It's a bit crude but I've essentially copied the code that generates the operation id and made a few tweaks. This is now available in beta3.
Let me know if you have any issues with it.

**Comment by senften** [comment]
Thanks, I appreciate it. I'll check it out. Last night I worked around the problem by adding SwaggerOperations to each endpoint, e.g. 
```
        [HttpPost]
        [Route("/api/v{api-version:apiVersion}/projects")]
        [Swashbuckle.AspNetCore.SwaggerGen.SwaggerOperation("CreateProject")]
        [ProducesResponseType(typeof(Project), 200)]
        [ProducesResponseType(typeof(void), 404)]
```

This worked well for me.

Also, FYI, I think Mvc.Versioning-rc1 has bigger problems.  After I cleaned up my naming, I was struggling with routing this morning which cleared up when I dropped back to beta2

```
    <!--<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="1.1.0-rc1"/>-->
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="1.1.0-beta2"/>
```

I'm forking the example code I mentioned above, updating it to the latest, and will open an issue over there.

**Comment by rh072005** [comment]
Your mention of using SwaggerOperation attributes got me thinking. It turns out the fix I'd added ends up overwriting any values set by these attributes. I've just fixed this and it's now available in beta4
