### ISSUE TITLE
 No service for type 'Microsoft.AspNetCore.Mvc.ApiExplorer.IApiVersionDescriptionProvider' has been registered.

### ISSUE THREAD

**Issue by huzaynbolt** [rh072005/SwashbuckleAspNetVersioningShim#16]
I get this error on running the project after adding the necessary snippets

**Comment by rh072005** [comment]
Do you have `services.AddMvc();` or  `services.AddMvcCore().AddVersionedApiExplorer();` in your Startup.cs?
Swashbuckle.AspNetCore depends on them so you may get this error without them
There's some more detail on this issue [Swashbuckle.AspNetCore #299](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/299)

**Comment by huzaynbolt** [comment]
I have added it, 

   string connectionString = Configuration.GetConnectionString("DefaultConnection");

            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddMvcCore().AddVersionedApiExplorer();
            services.AddApiVersioning(o =>
            {
                o.AssumeDefaultVersionWhenUnspecified = true;
                o.DefaultApiVersion = new ApiVersion(1,0);

            });



            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection")));
            services.AddDefaultIdentity<IdentityUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();

            //Business Logic Services for DI
            services.AddSingleton<ICategoryService>(sp => { return new CategoryService(connectionString); });


            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services.AddSwaggerGen(c =>
            {
                var provider = services.BuildServiceProvider().GetRequiredService<IApiVersionDescriptionProvider>();
                c.ConfigureSwaggerVersions(provider);
                c.SwaggerDoc("v1", new Info {Title = "My API", Version = "v1"}); 

            });

**Comment by huzaynbolt** [comment]
Error Stack

MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.SwaggerDoc(System.String, Swashbuckle.AspNetCore.Swagger.Info)'.
SwashbuckleAspNetVersioningShim.SwaggerVersioner.ConfigureSwaggerVersions(SwaggerGenOptions swaggerOptions, IApiVersionDescriptionProvider provider, string titleTemplate)
SwashbuckleAspNetVersioningShim.SwaggerVersioner.ConfigureSwaggerVersions(SwaggerGenOptions swaggerOptions, IApiVersionDescriptionProvider provider)
CampusJobsWeb.Startup+<>c__DisplayClass4_0.<ConfigureServices>b__4(SwaggerGenOptions c) in Startup.cs
+
                c.ConfigureSwaggerVersions(provider);
Microsoft.Extensions.Options.ConfigureNamedOptions<TOptions>.Configure(string name, TOptions options)
Microsoft.Extensions.Options.OptionsFactory<TOptions>.Create(string name)
Microsoft.Extensions.Options.OptionsManager<TOptions>+<>c__DisplayClass5_0.<Get>b__0()
System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
System.Lazy<T>.ExecutionAndPublication(LazyHelper executionAndPublication, bool useDefaultConstructor)
System.Lazy<T>.CreateValue()

**Comment by huzaynbolt** [comment]
@rh072005 Any update on this issue?

**Comment by rh072005** [comment]
I think this might now be the same as issue #14 
Which versions of dotnet & Swashbuckle.AspNetCore are you using?
