### ISSUE TITLE
NuGet package dependency issue

### ISSUE THREAD

**Issue by davelovesoftware** [rh072005/SwashbuckleAspNetVersioningShim#5]
Thanks for making this package! Solved a big issue for me. But I did notice one problem:

The NuGet packager version 0.4.2-pre declares a dependency on Microsoft.AspNetCore.Mvc.Versioning 1.0.3 or greater but fails at runtime without version 1.1.0-beta1.

**Comment by davelovesoftware** [comment]
Sorry, never mind. It looks like the NuGet package dependency is set at 1.1.0-beta1. My problem was a quirk in how NuGet restores packages.

I was using SwashbuckleAspNetVersioningShim in a base library. The actual api project depended on that base lib and Microsoft.AspNetCore.Mvc.Versioning at version 1.0.3 but not SwashbuckleAspNetVersioningShim. NuGet apparently didn't force my api project's dependency version up. Probably because it is trying to prevent going from a non-pre-release version to a pre-release version.

Sorry for the trouble!

**Comment by rh072005** [comment]
@bungeemonkee Glad it's proving helpful :smile: 
As a heads up; when Swashbuckle.AspNetCore comes out of pre-release what I'll probably do is drop the Microsoft.AspNetCore.Mvc.Versioning version back down to the latest stable version (assuming 1.1.0 hasn't come out of pre-release by then). This will let me get a non pre-release version of SwashbuckleAspNetVersioningShim out. At the same time I'll also release another pre-release version with the higher version of Microsoft.AspNetCore.Mvc.Versioning back in.
