### ISSUE TITLE
'IServiceCollection' does not contain a definition for 'AddMvc' & 'BuildServiceProvider'

### ISSUE THREAD

**Issue by RoryMcCrossan** [rh072005/SwashbuckleAspNetVersioningShim#9]
I've followed your guide and added the required using statement and code blocks to the Startup.cs file of a brand new project and am receiving the two errors mentioned above. Am I missing any references? It seems unlikely given that the Nuget package for this shim seems to have added a *lot* of references already.

Here's what I'm seeing if it makes the issue clearer: http://i.imgur.com/0G6iNTU.png

**Comment by PaddoSwam** [comment]
You'll need to add the `Microsoft.AspNetCore.Mvc` package aswell or atleast add the using.

**Comment by rh072005** [comment]
@RoryMcCrossan these 2 methods should come out of the box when you create an ASP.NET Core web app. As @PaddoSwam says you'll need to make sure that ``Microsoft.AspNetCore.Mvc`` is referenced. This should get added automatically but it sounds like it hasn't been in this case.

**Comment by RoryMcCrossan** [comment]
Thanks. I created the solution as an empty WebApi project. Adding that reference fixed the error, although the swagger output is now completely empty. I just get the API title and no endpoints listed. I didn't realise when I pulled this repo that it was for AspNetCore - so that's my mistake. I need this for .Net 4.6.
